
    /**
     * Auto Generated by @collabur/ds-scripts on every build
     * Manually Updating is NOT advised
     */

    
        export const config = {"brandTitle":"Jason DS Localhost","brandUrl":"/","brandImage":"http://res.cloudinary.com/collabur/image/upload/txyuf0p3pjtxz6xx0olk"};
        
  