name: Collabur App NPM Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup GIT
        run: |
          git switch -c $GIT_BRANCH
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
        env:
          GIT_BRANCH: ${{ secrets.COLLABUR_DS_BRANCH }}
      - name: Update package name and version
        run: |
          npm install -g json
          json -I -f package.json -e "this.name=\"$PACKAGE_NAME\""
          json -I -f package.json -e "this.version=\"$PACKAGE_VERSION\""
        env:
          PACKAGE_NAME: ${{ secrets.NPM_PACKAGE_NAME }}
          PACKAGE_VERSION: ${{ secrets.NPM_PACKAGE_VERSION }}
      - name: Git push
        run: |
          git add .
          git commit -m "release npm" -n
          git push --set-upstream origin
      - name: Install and Publish
        run: |

      - name: Expose ENV Variables
        run: |
          echo COLLABUR_DS=${{ secrets.COLLABUR_DS }} >> $GITHUB_ENV
          echo COLLABUR_DS_BRANCH=${{ secrets.COLLABUR_DS_BRANCH }} >> $GITHUB_ENV
          echo COLLABUR_ACCESS_TOKEN=${{ secrets.COLLABUR_ACCESS_TOKEN }} >> $GITHUB_ENV
          echo COLLABUR_API=${{ secrets.COLLABUR_API }} >> $GITHUB_ENV
      - name: Install & Build
        run: |
          npm install --frozen-lockfile --ignore-scripts
          npm run build
        env:
          CI: true
      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken=$AUTH_TOKEN
          npm publish --access $NPM_ACCESS
        env:
          CI: true
          AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          NPM_ACCESS: ${{ secrets.NPM_ACCESS }}
