name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install & Build
        run: |
          npm install --frozen-lockfile --ignore-scripts
          npm run build
        env:
          CI: true
      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken=$AUTH_TOKEN
          npm publish --access $NPM_ACCESS
        env:
          CI: true
          AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          NPM_ACCESS: ${{ secrets.NPM_ACCESS }}
